name: Trigger auto deployment for karttest

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/karttest-AutoDeployTrigger-917f5ea5-1340-4bbd-8021-913a2c8fc1e9.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: karttest.azurecr.io
          username: ${{ secrets.KARTTEST_REGISTRY_USERNAME }}
          password: ${{ secrets.KARTTEST_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: karttest.azurecr.io/karttest:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.KARTTEST_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n karttest -g DefaultResourceGroup-NEU --server karttest.azurecr.io --username  ${{ secrets.KARTTEST_REGISTRY_USERNAME }} --password ${{ secrets.KARTTEST_REGISTRY_PASSWORD }}
            az containerapp update -n karttest -g DefaultResourceGroup-NEU --image karttest.azurecr.io/karttest:${{ github.sha }}
